"""Replaceable, authorized external capability contracts."""

from congeries_core.policy.authorization import ActionRef

from .context import (
    CONTEXT_CAPABILITIES_ACTION,
    CONTEXT_PROVIDE_ACTION,
    ContextBinding,
    ContextBudget,
    ContextCapabilities,
    ContextCompleteness,
    ContextCompletenessPolicy,
    ContextEntry,
    ContextKey,
    ContextMergePolicy,
    ContextMergeRegistry,
    ContextMergeStrategy,
    ContextProvider,
    ContextProviderRegistry,
    ContextRequest,
    ContextRequirement,
    ContextResolver,
    ContextResult,
    ContextScopePattern,
    ContextUsage,
    ContextWarning,
    ResolvedContext,
    context_actions,
)
from .events import NullProviderEventPublisher, ProviderEventPublisher
from .model import (
    MODEL_CAPABILITIES_ACTION,
    MODEL_GENERATE_ACTION,
    MODEL_STREAM_ACTION,
    ModelBinding,
    ModelBudget,
    ModelCapabilities,
    ModelCapabilityRequirements,
    ModelEvent,
    ModelEventType,
    ModelFinishReason,
    ModelGateway,
    ModelOperation,
    ModelProvider,
    ModelProviderRegistry,
    ModelRequest,
    ModelRequestPolicy,
    ModelResponse,
    ModelSelector,
    ModelUsage,
    ToolCallProposal,
    model_actions,
)


def provider_actions() -> tuple[ActionRef, ...]:
    return (*context_actions(), *model_actions())


__all__ = [
    "CONTEXT_CAPABILITIES_ACTION",
    "CONTEXT_PROVIDE_ACTION",
    "MODEL_CAPABILITIES_ACTION",
    "MODEL_GENERATE_ACTION",
    "MODEL_STREAM_ACTION",
    "ContextBinding",
    "ContextBudget",
    "ContextCapabilities",
    "ContextCompleteness",
    "ContextCompletenessPolicy",
    "ContextEntry",
    "ContextKey",
    "ContextMergePolicy",
    "ContextMergeRegistry",
    "ContextMergeStrategy",
    "ContextProvider",
    "ContextProviderRegistry",
    "ContextRequest",
    "ContextRequirement",
    "ContextResolver",
    "ContextResult",
    "ContextScopePattern",
    "ContextUsage",
    "ContextWarning",
    "ModelBinding",
    "ModelBudget",
    "ModelCapabilities",
    "ModelCapabilityRequirements",
    "ModelEvent",
    "ModelEventType",
    "ModelFinishReason",
    "ModelGateway",
    "ModelOperation",
    "ModelProvider",
    "ModelProviderRegistry",
    "ModelRequest",
    "ModelRequestPolicy",
    "ModelResponse",
    "ModelSelector",
    "ModelUsage",
    "NullProviderEventPublisher",
    "ProviderEventPublisher",
    "ResolvedContext",
    "ToolCallProposal",
    "context_actions",
    "model_actions",
    "provider_actions",
]
