"""Transport-neutral MCP Adapter contracts and existing-boundary facades."""

from .composition import validate_mcp_composition
from .integration import (
    MCP_DISCOVERY_COMPLETED,
    MCP_DISCOVERY_FAILED,
    MCP_DISCOVERY_STARTED,
    MCP_INVOCATION_COMPLETED,
    MCP_INVOCATION_FAILED,
    MCP_INVOCATION_STARTED,
    McpContextProviderFacade,
    McpContextProviderImplementation,
    McpToolExecutor,
    mcp_actions,
)
from .mapping import (
    canonical_schema_digest,
    validate_context_binding,
    validate_discovery,
    validate_tool_binding,
)
from .model import (
    MCP_ADAPTER_CONTRACT_VERSION,
    MCP_PROTOCOL_VERSION,
    McpAdapterDescriptor,
    McpAdapterImplementation,
    McpContextBinding,
    McpDiscoverySnapshot,
    McpRemoteResource,
    McpRemoteTool,
    McpResourceRequest,
    McpResourceResponse,
    McpServerInfo,
    McpToolBinding,
    McpToolRequest,
    McpToolResponse,
    McpTransport,
)

__all__ = [
    "MCP_ADAPTER_CONTRACT_VERSION",
    "MCP_DISCOVERY_COMPLETED",
    "MCP_DISCOVERY_FAILED",
    "MCP_DISCOVERY_STARTED",
    "MCP_INVOCATION_COMPLETED",
    "MCP_INVOCATION_FAILED",
    "MCP_INVOCATION_STARTED",
    "MCP_PROTOCOL_VERSION",
    "McpAdapterDescriptor",
    "McpAdapterImplementation",
    "McpContextBinding",
    "McpContextProviderFacade",
    "McpContextProviderImplementation",
    "McpDiscoverySnapshot",
    "McpRemoteResource",
    "McpRemoteTool",
    "McpResourceRequest",
    "McpResourceResponse",
    "McpServerInfo",
    "McpToolBinding",
    "McpToolExecutor",
    "McpToolRequest",
    "McpToolResponse",
    "McpTransport",
    "canonical_schema_digest",
    "mcp_actions",
    "validate_context_binding",
    "validate_discovery",
    "validate_mcp_composition",
    "validate_tool_binding",
]
